active: AMQP_ACTIVE
user: AMQP_USER
password: AMQP_PASSWORD
hosts:
  __name: AMQP_HOSTS
  __format: json
tls:
  __name: AMQP_TLS
  __format: boolean
vhost: AMQP_VHOST
heartbeatIntervalInSeconds: AMQP_HEARTBEAT_INTERVAL_IN_SECONDS
reconnectTimeInSeconds: AMQP_RECONNECT_TIME_IN_SECONDS
